version: "3.9"

services:
  app:
    build: .
    container_name: flask_app
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: meuappdb
      MYSQL_USER: app_user
      MYSQL_PASSWORD: senha_app
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
